@url = https://localhost:44345/

###
# @name sign_in
POST {{url}}/signIn
Content-Type: application/json

{
    "MobileNumber": "971554296326"
}

### 
@accessToken = {{sign_in.response.body.$.accessToken}}

###
POST {{url}}/notification
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "Rafi",
    "message": "Hi how are you"
}
